name: Vandenberg Launch Digest

on:
  schedule:         # runs daily at 14:00 UTC (07:00 PDT)
    - cron:  '0 14 * * *'
  workflow_dispatch:   # lets you trigger it manually from the UI

jobs:
  digest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: pip install requests pytz

      - name: Send e-mail
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          DEST_EMAIL: ${{ secrets.DEST_EMAIL }}
        run: python send_digest.py
